pipeline:

  engine:
    image: php:5.6
    commands:
      - apt-get update
      - apt-get install -y git libssl-dev pkg-config
      - pecl install mongodb
      - echo 'extension=mongodb.so' > /usr/local/etc/php/php.ini
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - php composer.phar install --ignore-platform-reqs
      - bin/phpspec run 


