
<div class="tos">
   
	<div class="tos-scroll" style="overflow:scroll; height:200px; border:1px solid #DDD;padding:16px;margin-bottom:12px;">
	  	<p>Terms of Service &ndash;<br /> Minds Partnership Program</p>
		<p><strong>If you have been invited to participate in and have opted into our Minds Partnership program (the "Program"), and your participation in The Program has not been terminated, then the following terms shall apply.</strong> By participating in The Program you agree to become bound by the terms and conditions herein (&ldquo;The Agreement&rdquo;). If you do not agree to all of the terms and conditions herein you may not participate in The Program and are not eligible to receive The Program services (including, but not limited to, Program payments). To the extent that these terms and conditions are considered an offer on behalf of Minds, acceptance of such offer is expressly limited to these terms.</p>
		<p>You will comply with all all of the terms and conditions contained in the <a href="/p/terms">Minds Terms of Service</a> and all other operating rules, policies, and procedures that may be published from time to time by Minds.</p>
		<p>You will disclose to Minds any paid products or services you employ to refer paid hosting customers to Minds.</p>
		<p>You are not authorized to act as an agent of Minds and shall not so represent. You are not and shall not hold yourself out to be an employee of Minds.</p>
		<p>You may not factually misrepresent Minds, Minds.com or The Program including but not limited to, the services, products, and terms and conditions therefor.</p>
		<p>You hereby consent to the use of your name, likeness, blog name, and any associated content or logos by Minds in connection with advertisements, articles, and other similar communications conducted by Minds relating to the Program.</p>
		<p>You must be at least 18 years old to participate in the the Program. By agreeing to these terms, you represent that you are 18 or older.</p>
		<p>Program participants residing in the US must provide a tax ID.</p>
		<p>Subject to these terms of service, and provided that you are currently participating in the Program:</p>
		<p>Minds will pay you 50% of the revenue share of the hosting payments received by Minds by hosting customers who identify Your Minds.com username at the time of their initial registration. You are not entitled to revenue sharing payments from Minds.com hosting customers who fail to appropriately identify you at the time of their initial registration. Minds will issue payments approximately 45 days following the end of each month in which the applicable hosting payment(s) are received by Minds.</p>
		<p>All payments will be issued through a transaction medium determined by Minds in its sole discretion. You must conform with Minds chosen payment method(s) in order to be entitled to payment hereunder. Minds shall have no obligation to make any payment under this paragraph until the outstanding amount owed to you exceeds one hundred US dollars ($100). Your rights to Program payments that remain unclaimed or undeliverable for a period of one year or more may, in Minds sole discretion, be forfeit.</p>
		<p>If you wish to discontinue your participation in The Program, you may do so in the Minds.com settings page of your participating account. Minds will distribute remaining earnings to discontinued Program participants only if the amount exceeds twenty five US dollars ($25).</p>
		<p>Minds, in its sole discretion, may terminate your participation in The Program at any time, with or without cause, with or without notice, effective immediately.</p>
		<p>These terms of service are subject to change by Minds. Minds will take steps to notify you of changes via the Minds.com website or email. You are responsible for maintaining awareness and compliance with all future changes to these terms and conditions. If you do not agree to be bound by revised terms you must discontinue your participation in The Program immediately.</p>
		<p>The minds website and hosting services are provided &ldquo;as is&rdquo;. Minds and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither Minds nor its suppliers and licensors, makes any warranty that its website or hosting services will be error free.</p>
		<p>You represent and warrant that your participation in The Program will be in strict accordance with all applicable laws and regulations.</p>
		<p>You agree to indemnify and hold harmless Minds, its contractors, and its licensor, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys&rsquo; fees, arising out of your participation in The Program including but not limited to your violation of this Agreement.</p>
		<p><em>These Terms and Conditions constitute the entire agreement between Minds and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of Minds, or by the posting by Minds of a revised version. Except to the extent applicable law, if any, provides otherwise, these Terms and Conditions and/or your participation in The Program shall be governed by the laws of the state of Connecticut, U.S.A., excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. (&ldquo;JAMS&rdquo;) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in Hartford, Connecticut, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys&rsquo; fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties&rsquo; original intent, and the remaining portions will remain in full force and effect. A</em> <em>waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; Minds may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</em></p>
	</div>
  
   <input type="checkbox" name="accept_tos" id="accept_tos" <?= elgg_get_plugin_user_setting('accepted_partner_tos', elgg_get_logged_in_user_guid(), 'payments') == 'yes' ? 'checked="checked"' : '' ?> value="yes"/> <label for="accept_tos">I accept</label>
   
   <br/>
 <br/>
	
	<input type="submit" value="Save" class="elgg-button elgg-button-action"/>
</div>
